[[customizations.user]]
name = "root"
shell = "/usr/bin/fish"

[[customizations.user]]
name = "acardace"
# Password is 'fedora' - MUST be changed after installation
password = "$6$A6rc9m6f/aacBkAe$3Jnmlfb0YZsmWgZCcXyV/iaMgtmhRDZoSJeNwpG2gukEujBZ/NtAsOB4sHCbgGPJERa9HhW.B6uviTYNFUWB//"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeHlYMy97S9KKda5QdORi6wujhntAoFXIbfrF+rn9CK antonio@mushu"
groups = ["wheel", "libvirt"]
shell = "/usr/bin/fish"
