name: "Build Fedora Gaming bootc image"

env:
  IMAGE_NAME: "fedora-gaming"
  REGISTRY: "ghcr.io/${{ github.repository_owner }}"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'Containerfile.minimal'
      - 'rootfs/**'
      - 'host-scripts/**'
      - 'spec_files/**'
      - '.github/workflows/image.yml'
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'Containerfile.minimal'
      - 'rootfs/**'
      - 'host-scripts/**'
      - 'spec_files/**'
      - '.github/workflows/image.yml'
  schedule:
    - cron: '0 0 */2 * *'

permissions:
  contents: read
  packages: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build minimal image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: minimal
          containerfiles: Containerfile.minimal
          layers: true
          oci: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push minimal image to GHCR
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: minimal

      - name: Build full image
        uses: redhat-actions/buildah-build@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: Containerfile
          layers: true
          oci: true

      - name: Push full image to GHCR
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: latest ${{ github.sha }}